development:
  dialect: postgres
  database: todo2_development
  user: todo2
  password: foobar
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://todo2:foobar@127.0.0.1:5432/todo2_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://todo2:foobar@127.0.0.1:5432/todo2_production?sslmode=disable"}}
